const Images = {
    cod: require('./cod.png'),
    fashion: require('./fashion.png'),
    gratis_voucher: require('./gratis_voucher.png'),
    lainnya: require('./lainnya.png'),
    murah_lebay: require('./murah_lebay.png'),
    semua_promo: require('./semua_promo.png'),
    shopee_barokah: require('./shopee_barokah.png'),
    shopee_lokal: require('./shopee_lokal.png'),
    shopee_mall: require('./shopee_mall.png'),
    shopee_pulsa: require('./shopee_pulsa.png'),
    supermarket: require('./supermarket.png'),
    pay_later: require('./pay_later.png'),
    games: require('./games.png'),
    food: require('./food.png'),
    pay_sekitar: require('./pay_sekitar.png'),
    flashsale: require('./flashsale.png'),
    banner_1: require('./banner_1.png'),
    main_banner_1: require('./main_banner_1.png'),
    main_banner_2: require('./main_banner_2.jpeg'),
    main_banner_3: require('./main_banner_3.jpeg'),
    main_banner_4: require('./main_banner_4.png'),
    main_banner_5: require('./main_banner_5.png'),
    main_banner_6: require('./main_banner_6.png'),
    product_1: require('./product_1.png'),
    product_2: require('./product_2.png'),
    fire_icon: require('./fire-icon.png'),
    gratis_ongkir_extra_cashback: require('./gratis_ongkir_cashback_extra.png'),
    gratis_ongkir_extra_instan: require('./gratis_ongkir_extra_instan.png'),
    gratis_ongkir_complete: require('./gratis_ongkir_comlete.png'),
    mall_text: require('./mall-text.png'),
}

export default Images