const Images = {
    cod: require('./cod.png'),
    fashion: require('./fashion.png'),
    gratis_voucher: require('./gratis_voucher.png'),
    lainnya: require('./lainnya.png'),
    murah_lebay: require('./murah_lebay.png'),
    semua_promo: require('./semua_promo.png'),
    shopee_barokah: require('./shopee_barokah.png'),
    shopee_lokal: require('./shopee_lokal.png'),
    shopee_mall: require('./shopee_mall.png'),
    shopee_pulsa: require('./shopee_pulsa.png'),
    supermarket: require('./supermarket.png'),
    pay_later: require('./pay_later.png'),
    games: require('./games.png'),
    food: require('./food.png'),
    pay_sekitar: require('./pay_sekitar.png'),
    banner_1: require('./banner_1.png'),
    main_banner_1: require('./main_banner_1.png'),
    main_banner_2: require('./main_banner_2.jpeg'),
    main_banner_3: require('./main_banner_3.jpeg'),
    main_banner_4: require('./main_banner_4.png'),
    main_banner_5: require('./main_banner_5.png'),
    main_banner_6: require('./main_banner_6.png'),
}

export default Images